/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'connexo';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String AMIT_GURU = 'assets/dummy/amit_guru.jpg';
  static const String DUMMY_PROFILE = 'assets/dummy/dummy_profile.jpg';
  static const String IC_IMAGE = 'assets/images/ic_image.png';
  static const String IC_PROFILE = 'assets/images/ic_profile.png';
  static const String LOGO = 'assets/images/logo.png';
  static const String NO_WIFI = 'assets/images/no_wifi.png';
  static const String PAGE_NOT_FOUND = 'assets/json/page_not_found.json';
  static const String EMPTY_LOTTIE = 'assets/lottie_jsons/empty_lottie.json';
  static const String ERROR_LOTTIE = 'assets/lottie_jsons/error_lottie.json';
}
